sonar.projectKey=rcstrue_php_payroll
sonar.organization=rcstrue

sonar.projectName=PHP Payroll
sonar.projectVersion=1.0

sonar.sources=.

sonar.language=php

# Exclude unnecessary folders
sonar.exclusions=vendor/**,node_modules/**,.github/**,database/**,upload/**,skills/**,.next/**

# Encoding
sonar.sourceEncoding=UTF-8

# PHP-specific settings
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=phpunit.xml

# Analysis scope
sonar.inclusions=**/*.php
sonar.test.inclusions=**/*Test.php,**/*test.php

# Quality gates
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
